### ISSUE TITLE
[Bug] shell login option drops me to a blinking cursor, not bash

### ISSUE THREAD

**Issue by mchaker** [fairyglade/ly#665] opened 2024-07-29 04:57 UTC
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

1.1.0

### Observed behavior

When running `ly`, and selecting "shell" login as the "other" field, I can log in (get past the `ly` screen) but then I get dropped to a blank cursor, not even showing a bash prompt. Is there some missing config I need to set up in order to use plaintext mode?

![image](https://github.com/user-attachments/assets/ac6c7ac0-e03b-472b-81d0-c55e93364fc4)
![image](https://github.com/user-attachments/assets/8e6d4326-5f34-4bf6-9c61-7dfdd6c47d1c)

### Expected behavior

I expected to be placed into a bash prompt, just like regular plaintext mode used to work on login, prior to installing `ly`.

### Steps to reproduce

1. select "shell" as the login method
2. log in
3. get dropped into empty screen

### Relevant logs

```shell
OS debian 12, x86_64
```

**Comment by port19x** [comment] 2024-07-29 07:47
Can confirm on arch linux

**Comment by AnErrupTion** [comment] 2024-07-29 09:02
@mchaker @port19x I can reproduce this issue on both Debian 12 and Arch Linux. Now, after much tinkering, changing the shell to Fish worked, but Bash or Dash didn't want to work. Or well, that's what I thought... I realized that, in the TTY, I can still execute commands:

![image](https://github.com/user-attachments/assets/eebfac17-2e27-441e-8123-08abc4ed6e32)

I can do this on both Debian and Arch. Can you guys confirm that's the case?

**Comment by AnErrupTion** [comment] 2024-07-29 10:17
Okay, I finally identified the problem. It's due to PR #621, which redirected `StandardError` to systemd's journal, but of course, only with systemd. A fix is to modify the service and change the following:

```diff
- StandardError=journal
```

I tried looking online, but unfortunately it doesn't seem like you can direct the output to 2 places at the same time.

**Comment by mchaker** [comment] 2024-07-29 10:43
Confirming that is the case - I can run commands up until I hit "Ctrl-C" or "Ctrl-D".

I will test modifying the service as you described and report back.

**Comment by mchaker** [comment] 2024-07-29 11:03
Confirming that modifying the service as described works!

![image](https://github.com/user-attachments/assets/5ca0e1e8-d2f4-4538-82e9-310e4ceb3f60)
![image](https://github.com/user-attachments/assets/bbc3de8e-0526-436b-88ce-ab92e654f0d8)

**Comment by AnErrupTion** [comment] 2024-07-29 11:05
> I'm not sure if the manual fix is compatible with GUIs/DEs, so not sure what code changes need to happen here, but the manual fix does work :)

It is fully compatible, as the previously mentioned PR was a simple one-line change anyway.

**Comment by AnErrupTion** [comment] 2024-07-29 11:34
I've pushed the fix just in case, and I'll also backport it for v1.0.2. I'll leave the issue open so that port19x can verify if it works on their part.

**Comment by AnErrupTion** [comment] 2024-08-04 15:13
@port19x Ly v1.0.2 hit the repos, can you confirm the bug is fixed on your side please?

**Comment by mchaker** [comment] 2024-08-04 17:08
unexpected behavior: after pulling from master, rebuilding, reinstalling, now logging out leaves the past session on the screen, behind the ly login window: is that expected?

![image](https://github.com/user-attachments/assets/31be95a4-acc8-4530-9d94-bc1717ba8a36)

**Comment by AnErrupTion** [comment] 2024-08-04 17:44
> unexpected behavior: after pulling from master, rebuilding, reinstalling, now logging out leaves the past session on the screen, behind the ly login window: is that expected?
> 
> ![image](https://private-user-images.githubusercontent.com/10101544/354917481-31be95a4-acc8-4530-9d94-bc1717ba8a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTM0MzMsIm5iZiI6MTcyMjc5MzEzMywicGF0aCI6Ii8xMDEwMTU0NC8zNTQ5MTc0ODEtMzFiZTk1YTQtYWNjOC00NTMwLTlkOTQtYmMxNzE3YmE4YTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYjU5NGU5NmJjNzc1YjIxZDAzMzJhM2UxODZjYWUwZGVhMGQyNjIyYTQxOGNjZjNmNTY1NGJlMmZlMTIyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYgGk3GhAdwzhFu66t8bBM_ZDB7XrF9vY451kCDRNuI)

That's definitely a bug. I'll try to reproduce it and hunt it down.

**Comment by AnErrupTion** [comment] 2024-08-04 18:43
@mchaker This should be fixed with the latest commit. Can you check on your machine please?

**Comment by mchaker** [comment] 2024-08-04 18:50
Checking now, will report back with results.

**Comment by mchaker** [comment] 2024-08-04 18:55
This bug seems fixed - the console is now cleared when logging out of a shell login session :)

**Comment by port19x** [comment] 2024-08-04 21:44
Tomorrow

**Comment by port19x** [comment] 2024-08-05 08:51
I can confirm shell login now working flawlessly on arch linux with bash (my current login shell).

I'd say you can safely close this issue now

**Closed** 2024-08-05 10:07 UTC
Labels: bug
