### ISSUE TITLE
[Feature Request] manpage

### ISSUE THREAD

**Issue by jrcharney** [fairyglade/ly#438] opened 2022-09-01 18:48 UTC
`ly` has some great potential, but `RTFM` and starting up `ly` is probably not the best way to respond to `ly --help`.

Considering how popular this project is getting, it might be time to write up a manpage for `ly` so that `man ly` can offer us some *man-ly* advice on how to use it. :grin:

**Comment by Cavernosa** [comment] 2022-09-01 23:20
The RTFM is already replaced with something more useful in the last git
A manpage I agree it could be kinda useful

**Comment by jrcharney** [comment] 2022-09-01 23:25
At very least, add a URL next to "RTFM" so we can at least have a quick reference to where it is.

**Comment by AnErrupTion** [comment] 2022-09-02 22:17
Personally, I don't think a manpage is really that useful. The config file is well documented enough that any person could figure out what setting does what, and doing ``ly --help`` redirects you to the config file.

**Comment by jrcharney** [comment] 2022-09-03 04:56
Well, I do think it would be important for `ly` not to launch if my curiosity to try `-h` or `--help` to see if there's any information about how I should use it (without coming to Github).  Fortunately, a CTRL+C in the shell I was using let me exit out. Imagine it I couldn't do that or didn't know that was possible.

All I'm saying is to probably make a couple of simple modifications to avoid making mistakes of launching `ly` without getting it properly set up first.

**Comment by AnErrupTion** [comment] 2022-09-03 11:56
Wait, do you mean doing ``ly --help`` launches a login prompt for you? If yes, this should not happen at all.

**Comment by Cavernosa** [comment] 2022-09-03 14:37
I can confirm `ly --help` launches ly normally for me as well (except that the help message is printed), I have to Ctrl-c to exit ly and view the printed message. Thought this was intended behavior lol

**Comment by AnErrupTion** [comment] 2024-05-04 20:04
I personally thik the configuration file is already well documented. The aforementionned bug is also fixed, so I'm closing this issue as solved.

**Closed by AnErrupTion** 2024-05-04 20:04 UTC
Labels: feature
