### ISSUE TITLE
Fingerprint reader login

### ISSUE THREAD

**Issue by h1divp** [fairyglade/ly#625] opened 2024-06-23 14:08 UTC
I think adding the ability to use fingerprint readers for login would be useful, but maybe not as a feature enabled by default.

Maybe this adds too much complexity or distro specific dependencies to this project? I would like to hear some thoughts about this from people with more experience than me. Maybe some kind of workaround that could still work with Ly could be mentioned in the documentation at the very least.

I just think that the reader on my laptop sits too dormant...

Discussion is appreciated.

**Comment by AnErrupTion** [comment] 2024-07-04 11:23
Duplicate of issue #227. All that should be needed in theory is a PAM module added in `/etc/pam.d/ly`, but it needs further investigation.

**Closed by AnErrupTion** 2024-07-04 11:23 UTC
