### ISSUE TITLE
config file being ignored on debian

### ISSUE THREAD

**Issue by mchaker** [fairyglade/ly#467] opened 2022-12-06 07:48 UTC
Installed via git

`/etc/ly/config.ini` exists

changing any value does nothing (trying to enable animation)

is there a bug on debian that prevents `/etc/ly/config.ini` from being respected?

**Comment by AnErrupTion** [comment] 2022-12-07 11:22
> is there a bug on debian that prevents /etc/ly/config.ini from being respected?

Not that I know of...

**Comment by mchaker** [comment] 2022-12-07 20:06
I've tried running https://github.com/kiedtl/fire on the same machine, and it works.

So I've narrowed it down to the `/etc/ly/config.ini` file not being read by `ly` for some reason.

Any way I can help debug?

**Comment by mindsDevCom** [comment] 2022-12-07 20:30
Did you tried to restart ly.service after changing the config file?
`systemctl restart ly.service` (The command will log you out!)

**Comment by mchaker** [comment] 2022-12-07 23:19
I tried modifying the code directly -- `draw.c`, `config_defaults()`

and that worked

so it is definitely not reading the config file :(

**Comment by mindsDevCom** [comment] 2022-12-07 23:58
I just tried to change the configuration and it seems to work.
Might sound stupid (I actually did this mistake at first) but could it be that you did not changed the value of _animate_ but just uncommented the line? It's default value is false!

**Comment by mchaker** [comment] 2022-12-08 14:50
I tried again, and yes I did change the value of animate to true every time, not just uncomment it :( 

Still definitely does not work

**Comment by elliotnash** [comment] 2022-12-27 18:05
My config file is also not being read - on arch linux, arm64

**Comment by docteurzoidberg** [comment] 2023-02-10 02:52
> My config file is also not being read - on arch linux, arm64

exact same thing for me , armbian jammy. linux arm64

**Comment by Thiago-Assis-T** [comment] 2023-04-06 18:48
Same thing on arch with the ly-git package from the AUR

**Comment by port19x** [comment] 2023-04-24 12:14
> Same thing on arch with the ly-git package from the AUR

Can confirm, not working on arch

**Comment by mchaker** [comment] 2023-05-02 04:49
@AnErrupTion This issue seems to be widespread... I'm hoping you can get a chance to take a look sometime. I would like to use ly on debian

**Comment by AnErrupTion** [comment] 2024-05-04 19:54
Sorry for the way too late answer. Ly seems to have a non-negligeable amount of issues on non-x86 systems. If the Zig rewrite doesn't fix these issues, I'll try to look at them.

**Comment by mchaker** [comment] 2024-05-04 20:54
Thank you so much! No rush, everything is appreciated! :)

**Comment by AnErrupTion** [comment] 2024-07-27 19:40
@mchaker @elliotnash @docteurzoidberg @Thiago-Assis-T @port19x Speaking of the Zig rewrite, could you guys now check if the issue is fixed with the latest code on master, please?

**Comment by Thiago-Assis-T** [comment] 2024-07-27 19:57
> @mchaker @elliotnash @docteurzoidberg @Thiago-Assis-T @port19x Speaking of the Zig rewrite, could you guys now check if the issue is fixed with the latest code on master, please?

sorry, i'm unable to check it, i'm now on nixos and won't be able to check it..

**Comment by SimonTank** [comment] 2024-07-27 22:00
@AnErrupTion It didn't work for me before, but I did the build and can confirm that the config file working.

OS: Debian GNU/Linux 12 (bookworm) x86_64
Kernel: 6.1.0-21-amd64

Thanks for the fix

**Comment by mchaker** [comment] 2024-07-29 03:08
I no longer have the machine this issue was filed about (iBook/powerbook -- 32-bit powerpc running debian 8),

however I spun up a QEMU VM to try powerpc debian 8. Unfortunately, zig does not distribute 32-bit powerpc binaries, and the available method to build zig from source requires gcc >= 7 or clang >= 6, both unavailable on 32-bit debian 8 for powerpc.

So, 32-bit powerpc is officially too old to use `ly` on :)

Ultimately, I am spinning up a 32-bit debian VM to see if building `ly` using 32-bit x86 zig will work.

**Comment by mchaker** [comment] 2024-07-29 04:42
Unfortunately, `ly` does not build on debian x86 32bit.

I did run `sudo apt install build-essential libpam0g-dev libxcb-xkb-dev` before running `zig build` in the `ly` repo root.

Since this is a plaintext VM, I can't copy text directly from the console, but I do have a screenshot of the `zig build` failure:
![image](https://github.com/user-attachments/assets/7b8e012b-fbd3-4d16-90bc-6462fb2854f0)

Good news, though, building and running `ly` on debian x86 64bit works, just like SimonTank posted above.

**Comment by port19x** [comment] 2024-07-29 07:56
The ly config file is no longer ignored on arch.
ly builds and runs fine given this new version.

In my testing I was able to reproduce #665 and opened #666

**Comment by mchaker** [comment] 2024-07-29 10:47
Right, to respond to the issue topic - ly on x86_64 debian now respects the config file.

**Comment by AnErrupTion** [comment] 2024-07-29 10:55
> Unfortunately, `ly` does not build on debian x86 32bit.
> 
> I did run `sudo apt install build-essential libpam0g-dev libxcb-xkb-dev` before running `zig build` in the `ly` repo root.
> 
> Since this is a plaintext VM, I can't copy text directly from the console, but I do have a screenshot of the `zig build` failure: ![image](https://private-user-images.githubusercontent.com/10101544/352910645-7b8e012b-fbd3-4d16-90bc-6462fb2854f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTAyNjIsIm5iZiI6MTcyMjI0OTk2MiwicGF0aCI6Ii8xMDEwMTU0NC8zNTI5MTA2NDUtN2I4ZTAxMmItZmJkMy00ZDE2LTkwYmMtNjQ2MmZiMjg1NGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEwNDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhN2NiMGQzMzViMGMyYzkyNmJhYzhmMTUwZTRkN2JiMDcxMjA2YzAzMTNmNzc0NzAyOTU2YWIzMjhlNjJkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIDHY1CTozWGE_XAhoJeYWWunpQSjxwpBU0vs7pg2eY)
> 
> Good news, though, building and running `ly` on debian x86 64bit works, just like SimonTank posted above.

That's a bug in Zig itself. Both `libpam` and `libxcb` are located in `/usr/lib/i386-linux-gnu`, but Zig doesn't search there.

**Comment by AnErrupTion** [comment] 2024-07-29 10:59
With that said, this issue seems to be resolved, so I'm closing it. :D

**Closed by AnErrupTion** 2024-07-29 10:59 UTC
Labels: bug

**Comment by mchaker** [comment] 2024-07-29 11:05
Thank you so much!

**Comment by antnesswcm** [comment] 2024-09-16 14:06
Is the version in the latest arch linux library the one that has been fixed, I still can't change the configuration

https://archlinux.org/packages/extra/x86_64/ly/

Build Date: | Aug. 2, 2024, 9:35 a.m. UTC

**Comment by AnErrupTion** [comment] 2024-09-28 19:38
@antnesswcm Can you please share your config file? It may not be parsed correctly.
