### ISSUE TITLE
Systemd Logind Session not closed correctly

### ISSUE THREAD

**Issue by moberrauch** [fairyglade/ly#165] opened 2020-01-20 16:01 UTC
When closing sway and successfully returning to ly, the user session I just logged out from is still running. It is listed under `loginctl` and therefore also the systemd runtime directory `/run/user/1000/` is still alive / mounted.

When I relog as the same user, fortunately not a new session is opened, but the old one reused, nevertheless some issues arise from this unclean session handling, specially with dbus (e.g. controlling Auryo via `playerctl` doesn't work anymore).

**Observed behaviour:**
`loginctl` lists the user session even after exiting back to ly.

**Expected behaviour:**
The login session is closed correctly as if it never had been opened (just like after a fresh system boot).

**Reproduce:**
Log into sway from ly and exit sway again. Log in from a different tty (preferably as a different user) and execute `loginctl` and / or look for the user's runtime directory.

**System:**
Arch Linux (linux-zen 5.4.13)
Systemd version: 244.1 with PAM support
ly version: 0.4.0
sway version: 1.2

I will do further testing, if desired.

**Comment by buckshee** [comment] 2020-03-06 17:19
You should be using some type of Session Manager, a hybrid like LightDM or configuring your DE to exit in the way you want.

**Comment by wolfhechel** [comment] 2020-12-18 15:49
I think this is a bad behaviour from ly regardless if you're using a session manager or not. The problem is that the pam_start and subsequently all pam_authentication calls are done in the root ly before forking it off to xorg. This makes systemd attach the root process of ly to XDG_SESSION_ID, meaning my user session is tied to the root process.

This has multiple consequences, first of all the it's impossible to reinitialize a session after for instance killing my WM. pam_systemd will simply exit with "Cannot create session: Already running in a session or user slice". My next session will then be left without a XDG_SESSION_ID initialized.
The second consequence is that if I do loginctl terminate-session $XDG_SESSION_ID ly simply exits. In most DM's I've come across the behaviour is that I'll return to login prompt (owned by root).

I'm working on a fix for this and will reference this issue once I've come up with a fix.

**Comment by massimopavoni** [comment] 2024-03-24 19:16
> I think this is a bad behaviour from ly regardless if you're using a session manager or not. The problem is that the pam_start and subsequently all pam_authentication calls are done in the root ly before forking it off to xorg. This makes systemd attach the root process of ly to XDG_SESSION_ID, meaning my user session is tied to the root process.
> 
> This has multiple consequences, first of all the it's impossible to reinitialize a session after for instance killing my WM. pam_systemd will simply exit with "Cannot create session: Already running in a session or user slice". My next session will then be left without a XDG_SESSION_ID initialized. The second consequence is that if I do loginctl terminate-session $XDG_SESSION_ID ly simply exits. In most DM's I've come across the behaviour is that I'll return to login prompt (owned by root).
> 
> I'm working on a fix for this and will reference this issue once I've come up with a fix.

I know this is a very old issue now, but it seems like the problem is still there, and it affects my ly + dwm combination, so is there even just a temporary fix, hoping that it can be changed later?

**Comment by AnErrupTion** [comment] 2024-07-27 19:02
@moberrauch @wolfhechel @massimopavoni Can you guys test if the issue is fixed with master, please?

**Comment by wolfhechel** [comment] 2024-08-09 05:50
@AnErrupTion yes! On 1.0.2 I return back to the login prompt after terminating my session, good job! Although the TTY2 is hammered with log output from my terminated session, but I reckon this to be another issue completely.

Go ahead and mark this issue as resolved.

**Comment by AnErrupTion** [comment] 2024-08-09 16:37
If anybody else keeps having this issue, please re-open one. Thanks!

**Closed by AnErrupTion** 2024-08-09 16:37 UTC
Labels: bug, ok
