### ISSUE TITLE
locale settings ignored

### ISSUE THREAD

**Issue by Phundrak** [fairyglade/ly#278] opened 2021-03-19 09:05 UTC
When I launch any session from ly (tested in my case with a shell session and Awesome), the locale set in `/etc/locale.conf` is not respected and all locales are set to `en_US.UTF-8`.
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
However, if I manually create a new session from any available TTY (such as TTY1), I get the correct output as set in my locale configuration, be it in the TTY console or in a graphical session started with `startx`.
```
$ locale
LANG=en_DK.UTF-8
LC_CTYPE="en_DK.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE=C
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_DK.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```
For the record, here is my `/etc/locale.conf` file:
```
LANG=en_DK.UTF-8
LC_COLLATE=C
LC_NAME=fr_FR.UTF-8
LC_NUMERIC=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MONETARY=fr_FR.UTF-8
LC_PAPER=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
```
I am currently running an up-to-date Arch Linux system with the package `ly 0.5.2-2`, and the output of `ly --version` is `Ly version v0.5.2.r0.g1523d08`.

I tested if a workaround was possible with a per-user locale config in `$XDG_CONFIG_HOME/locale.conf` (in my case `$HOME/.config/locale.conf`) [as instructed on the Arch Wiki](https://wiki.archlinux.org/index.php/Locale#Overriding_system_locale_per_user_session), but to no avail, I still get the same output when running `locale`.

**Comment by negativeExponent** [comment] 2021-03-19 10:37
i wonder if this is whats causing your issue:
https://github.com/Phundrak/dotfiles/blob/master/.etc/ly/config.ini#L38

try changing **lang = en** to **lang = fr** from your /etc/ly/config.ini (assuming you are using the config from your dotfile)

**Comment by Phundrak** [comment] 2021-03-19 11:06
My ly config from my dotfiles is not up to date with my actual ly config. The only meaningful line I have in my `/etc/ly/config.ini` is
```
blank_password = true
```
The rest is either comments or blank lines. So that is unfortunately not the source of this issue.

**Comment by negativeExponent** [comment] 2021-03-20 00:07
apparently, "lang" in config only affects language on ly's UI.

somewhat semi-related:
i too have issue with ly when LANG is null causing login to fail. Im not entirely sure systemd sources /etc/locale.conf before the shell starts but on the distro i use, /etc/locale is not source untill my shell starts (meaning after ly's login)

https://github.com/nullgemm/ly/issues/216#issuecomment-801525253

you can for the mean time source out the /etc/locale.conf as what the wiki already showed you to override whatever locale is being set.

**Comment by robertjk** [comment] 2021-05-01 12:18
I have similar problem. My `LC_MESSAGES` value set in `/etc/locale.conf` is not respected when using `ly`. It ends up being set to value of `LANG`, even though it should be different. I'm also using Arch.

**Comment by valentino-sm** [comment] 2022-05-15 05:37
I ran into the same problem

However I commented that string and everything works.
https://github.com/fairyglade/ly/blob/78e2fd1a214bae4c19788b2b3a27630ba4b48d8e/src/login.c#L223

It remains to find out where LANG variable comes from.

**Comment by negativeExponent** [comment] 2022-05-15 06:17
This should not have been merged because doing so will ignore system-configured /etc/profile locale as I've already stated above. Any system not using en_EN as.local will have some issues.

**Comment by Cavernosa** [comment] 2022-05-17 20:46
I'm having the same issue on Artix openrc. The only file defining LANG env vars is /etc/profile.d/locale.sh which runs after login.
It might be possible to mimick this file's behaviour (like [sddm did](https://github.com/sddm/sddm/blob/c257a40ba95f56b5f3830b923b1c56aa055cf8ea/src/auth/Auth.cpp#L118-L138))

**Comment by MaximMaximS** [comment] 2022-07-17 14:24
Does any1 have a temporary fix? This is the only thing that's preventing me from using ly...

**Comment by Cavernosa** [comment] 2022-07-17 17:27
> Does any1 have a temporary fix? This is the only thing that's preventing me from using ly...

> [valentino-sm](https://github.com/valentino-sm) commented on May 15
 I ran into the same problem
However I commented that line and everything works.
https://github.com/fairyglade/ly/blob/78e2fd1a214bae4c19788b2b3a27630ba4b48d8e/src/login.c#L223
It remains to find out where LANG variable comes from.

valentino-sm's fix worked for me as well.

**Comment by valentino-sm** [comment] 2022-11-06 06:20
@negativeExponent if the issue is arch-specific there could be the workaround in AUR package like:
`sed -i "/setenv(\"LANG\"/s/^/\/\//" src/login.c`

**Comment by hnorkowski** [comment] 2023-08-11 14:31
This issue is still a thing. I am having it on arch with Ly version v0.6.0.r0.g1c2be47.

**Comment by XorvatoAmigos** [comment] 2023-11-16 20:01
Unfortunately, the problem is current. 

```
Name            : ly
Version         : 0.6.0-1.1
```

**Comment by cameloper** [comment] 2024-01-02 18:33
Since this issue still persists I thought I'd explain how to apply @valentino-sm solution easily on arch in case anyone needs it:

1. Clone the package repo from Arch [using the pkgctl tool](https://wiki.archlinux.org/title/Arch_build_system#Using_the_pkgctl_tool)

```sh
pkgctl repo clone --protocol=https ly
cd ly
```

3. Change the `build()` method (line 41) as follows:
``` sh
build() {
    sed -i "/setenv(\"LANG\"/s/^/\/\//" $srcdir/ly/src/login.c
    make -C "$pkgname"
}
```

*so basically add the `sed` line*

4. Build and install the package [using makepkg](https://wiki.archlinux.org/title/Makepkg#Usage)

```sh
makepkg -si
```

Of course one could write a patch for this or automate it in some other way but it doesn't look like ly receives updates that often so it souldn't be too much work. 

P.S. I didn't explain much about the steps but I think becoming familiar with arch build/packaging system is pretty important anyway so I'd suggest taking a look at the links if you don't know what the commands do

**Comment by sluedecke** [comment] 2024-03-18 09:12
> Since this issue still persists I thought I'd explain how to apply @valentino-sm solution easily on arch in case anyone needs it:

Thanks @cameloper  and @valentino-sm, this solution works for me just fine.

**Closed** 2024-05-09 13:30 UTC
Labels: bug, needs review
