### ISSUE TITLE
Keyring isn't unlocked when logging in

### ISSUE THREAD

**Issue by KouranliKe** [fairyglade/ly#426] opened 2022-08-15 00:00 UTC
I don't really know if this is an issue or just a feature but, whenever I log in, I have to enter the password to my keyring if I open, for example, my internet browser. I just want ly to unlock it automatically. Any help? I use KDE Plasma in Arch Linux, kernel 5.19.1, and I use systemd.
(Sorry if my english is bad, I'm not a native speaker)

**Comment by AnErrupTion** [comment] 2022-08-15 19:08
Duplicate of #331. Even though it specifies the GNOME keyring, it is still the keyring, so it relates.

**Closed by AnErrupTion** 2022-08-15 19:08 UTC
