### ISSUE TITLE
Ly on ARM64 doesn't detect any session other than shell and xinitrc

### ISSUE THREAD

**Issue by marco-04** [fairyglade/ly#417] opened 2022-08-06 11:10 UTC
I compiled ly both on Arch and Debian (testing) ARM64 VMs, and contrarily to other display managers, like gdm, it didn't detect the session files residing in the "/usr/share/xsessions" directory. I tried with both Gnome and XFCE

**Comment by Cavernosa** [comment] 2022-08-07 03:18
Try using this version: https://github.com/fairyglade/ly/tree/da5b08abf28970db46ceaf95cd5bda48152799b1
I'm having the same issue after updating to the latest git version, some commit after da5b08a must have broken it.

**Comment by marco-04** [comment] 2022-10-02 00:58
Yeah, I have the same problem on Asahi Linux with a recursive clone

**Comment by marco-04** [comment] 2022-12-08 15:47
I probably did when I first tried it, but I can't confirm because now I can't even launch it anymore on Asahi, as it just crashes

**Comment by AnErrupTion** [comment] 2022-12-08 22:30
Ah, could you try now please? There was a *slight* mistake in the repo that's now fixed :D @marco-04

**Comment by marco-04** [comment] 2022-12-08 23:39
Just tried, and it doesn't work unfortunately. The same thing happens also for wayland sessions with those options uncommented from the /etc/ly/config.ini file

**Comment by PaddiM8** [comment] 2022-12-09 13:38
I'm experiencing the same thing, on aarch64

**Comment by PaddiM8** [comment] 2022-12-16 04:06
I experimented a bit and managed to get it to retrieve the sessions. Not sure if it breaks anything else, but... I added the following in `configator.c` in the configator submodule:

```
if (disc < 0) {
    i = 0;
}
```
on line 45.

The data seems to be retrieved correctly, but the configator search function doesn't end up *only* looking at index 1 when the length is 2. I don't know if this is a good fix, it just happened to make it work for me. I have never really used C.

**Comment by lucidph3nx** [comment] 2023-02-20 06:29
I can confirm that the solution by @PaddiM8 works with Asahi on M1 Mac booting a sway wayland session.

**Comment by mellowgeekcc** [comment] 2023-03-11 18:23
Yes, the solution also works on Raspberry 4 booting Xorg sessions.

**Comment by praxis88** [comment] 2023-03-19 21:00
can confirm this works on arch/manjaro arm

**Comment by AnErrupTion** [comment] 2024-05-04 20:10
I'm marking this issue as fixed for the Zig rewrite, since it doesn't use configator anymore.

**Closed** 2024-05-09 13:34 UTC
Labels: bug
