### ISSUE TITLE
Will Not Compile

### ISSUE THREAD

**Issue by d4140n-4h3-1** [fairyglade/ly#639] opened 2024-07-07 19:23 UTC
Line 28, Column 33; No field named "path" in union "Build.LazyPath".

**Comment by christian-heusel** [comment] 2024-07-08 09:54
This looks like a duplicate of #631

**Comment by AnErrupTion** [comment] 2024-07-12 20:30
> This looks like a duplicate of https://github.com/fairyglade/ly/issues/631

It indeed is!

**Closed by AnErrupTion** 2024-07-12 20:30 UTC
