### ISSUE TITLE
dwm Integration.

### ISSUE THREAD

**Issue by smhmd** [fairyglade/ly#122] opened 2019-09-19 20:19 UTC
I have a configured dwm with different colors, fonts, keybindings. logging in with ly is successful, but somehow it logs into vanilla dwm with all the defaults. this doesn't make sense. it is probably using the `config.def.h` somehow.
I have `.xinitrc` opening dwm in a loop:
```
while true; do
        dwm 2> ~/.dwm.log
        dwm >/dev/null 2>&1
done
``` 
so, I typically just enter my user name, then password and `startx` in the shell. why would dwm load in with default settings?

**Comment by cylgom** [comment] 2019-10-30 23:25
I think this is related to #121. Maybe this will be fixed once we handle utmp.

**Comment by cylgom** [comment] 2019-12-06 15:21
Could you give it another shot now #121 is fixed?

**Comment by alivefromupstairs** [comment] 2019-12-06 23:24
@cylgom The problem persists, unfortunately.

**Comment by FalyPr1nc3** [comment] 2020-02-15 12:01
Having the same issues with latest version

**Comment by FalyPr1nc3** [comment] 2020-02-20 12:01
Maybe i have found the root cause.
I am in Arch and besides a custom dmenu build i have the default dmenu version installed (as a dependency to clipmenu). In this case dmenu_run is located in` /usr/bin`.
Arch aliases `/bin` and `/sbin` to `/usr/bin`.
So since ly uses `/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin` default path, it finds the default version first, even `/usr/local/bin` stays before `/usr/bin`.

The solution is to flip path in config.ini:
`path = /usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin`

@aliveupstairs Could you check if you have the same root cause?

**Comment by FalyPr1nc3** [comment] 2020-02-20 12:19
@cylgom Would it be worth to have a bit more complex logic behind default path?
Like if /sbin and /bin are links, then put them to the end of PATH or even omit?

**Comment by aliveupstairs** [comment] 2020-02-23 01:27
@FalyPr1nc3 trying `ly` after some time, there is now the ability to login to `shell`. I just run `startx` in `~/.profile` if `tty2`. Since `xinit` does not work without additional parameters, I'm unable to run `xinitrc` option successfully (https://github.com/cylgom/ly/issues/181), so, I don't know if your solution is actually working since I'm not relying on `ly` to start X.

`ly` with `dwm` works on my end, @cylgom. Feel free to address Faly's observations or close the issue.

**Closed** 2024-07-27 20:11 UTC
Labels: bug, needs review

**Comment by jamescraft10** [comment] 2024-09-26 01:05
still doesnt work on dwm at least for me i get a permission denied error for .xinitrc

**Comment by AnErrupTion** [comment] 2024-10-19 16:33
@jamescraft10 Please open a separate issue with the most information you can. Thanks!
