### ISSUE TITLE
Gentoo (openrc) issue [SOLVED]

### ISSUE THREAD

**Issue by atrpwq** [fairyglade/ly#677] opened 2024-08-04 21:27 UTC
I git cloned ly and ran zig build install and all that stuff for openrc, i tried removing agetty and it returned a not found error, i didnt think much of it until i restarted and it booted into agetty, i went into etc/inittab and edited it a bit and it did not work it just left me in loop where i had to chroot from a usb. so how can i set it up for gentoo?

**Comment by AnErrupTion** [comment] 2024-08-04 21:48
@atrpwq The instructions in the README are correct. The "not found" error shouldn't be problematic either. In the `/etc/inittab` file, you should comment the line that looks like the following:

```
c2:2345:respawn:/sbin/agetty 38400 tty2 linux 
```

What is that "loop" you're talking about? Could you be a bit more precise on that, please?

**Comment by atrpwq** [comment] 2024-08-05 00:55
@AnErrupTion I followed some stupid tutorial online to figure it out after setting up dwm and gentoo, it ended up just throwing me into a constant loop where i couldnt login to xinitrc or xsession, and when i logged into shell to fix the the issue it kicked me to agetty then after a few  seconds it prompted me to ly. I got the usb i used to install gentoo and i had to chroot back into my install and delete the command i found online.

**Comment by atrpwq** [comment] 2024-08-05 00:58
@AnErrupTion https://youtu.be/9nspf7yapGY?si=_X3q42nI3UfVXQaA

**Comment by atrpwq** [comment] 2024-08-05 05:40
@AnErrupTion i deleted gentoo and installed artix with openrc and its still not working

**Comment by AnErrupTion** [comment] 2024-08-05 07:02
@atrpwq I'm able to run Ly on Artix OpenRC with XFCE. I simply ran:

```
# zig build installopenrc
# rc-update add ly
# rc-update del agetty.tty2
# rc-update del lightdm
```

Then Ly ran after reboot.

> ly 1.0.2 needs sudo privileges

I'm not sure what you're trying to do here. You shouldn't run it manually, the service will do that for you automatically.

**Comment by atrpwq** [comment] 2024-08-05 08:11
on boot, it required sudo priviledges, i ran whats in the codeblocks, and it failed. when i changed to an older version, it ran fine, but then agetty tty2 kept on loading without a purpose and interuppting not letting me login. on arch however, it runs perfectly fine.

**Comment by AnErrupTion** [comment] 2024-08-06 09:08
@atrpwq What failed when you ran the commands?

**Comment by atrpwq** [comment] 2024-08-06 10:37
@AnErrupTion nothing failed when i enter the commands, itd js be interupted by agetty tty2 (after i disabled it), and create some like weird bug, where i couldt enter my password and its just start freaking out.

**Comment by AnErrupTion** [comment] 2024-08-06 11:36
@atrpwq I'm honestly not sure how the TTY still appears for you (at least on Artix). I made a fresh install of Artix like I said before and installing Ly worked just fine. Is there something else you did I'm not aware of? I don't really understand...

**Comment by atrpwq** [comment] 2024-08-06 16:17
@AnErrupTion ill try it again with a vm

**Comment by atrpwq** [comment] 2024-08-06 16:33
@AnErrupTion reread the guide, i did it incorrectly, ill try it again and return whether it works or nah, thx tho

**Comment by atrpwq** [comment] 2024-08-06 18:01
@AnErrupTion same issue (i booted bare metal instead), just says "starting ly" then starts agetty.tty1

**Comment by atrpwq** [comment] 2024-08-06 18:06
i tried installing lightdm a few days ago on artix, i could be missing a package

**Comment by AnErrupTion** [comment] 2024-08-06 18:07
> @AnErrupTion same issue (i booted bare metal instead), just says "starting ly" then starts agetty.tty1

If you change the TTY, you also need to change it in Ly's config and must disable the right agetty service (if not already done, of course).

**Comment by atrpwq** [comment] 2024-08-06 18:18
@AnErrupTion i disabled agetty 2 as the guide told me, and i ran all the commands like zig build [installopenrc], rc-update add ly default and rc-update del agetty.tty2, still im left with an agettytty1 login screen, and now when i switch to tty2 it doesnt show agetty, just "Artix Linux... (tty2)

**Comment by atrpwq** [comment] 2024-08-06 18:31
is it fine to run these commands as sudo or no? if not then how do i uninstall it

**Comment by DoctorKnowsBetter** [comment] 2024-08-07 14:02
Found the problem! You forgot to assign the EXE_NAME variable in ly-openrc. Please fix it!!!

**Comment by DoctorKnowsBetter** [comment] 2024-08-07 14:28
https://github.com/fairyglade/ly/pull/681

**Comment by atrpwq** [comment] 2024-08-07 15:22
ah sweet, thanks doctor

**Comment by AnErrupTion** [comment] 2024-08-07 15:51
I have absolutely no idea how I forgot about this, but I did. And I'm even more confused about how it worked for me in a VM. Regardless, the issue is now fixed, so can you confirm this @atrpwq please?

**Comment by atrpwq** [comment] 2024-08-07 17:11
alr, ill try it again but ill have to dual boot artix with arch (OS i got now) ill come back with the results :)), btw maybe it was different on the virtual machine cus u got the stable iso (last updated a year ago)

**Comment by atrpwq** [comment] 2024-08-07 17:12
@AnErrupTion btw since this is a bug fix, is it added onto v1.0.2 (says last updated 6 days ago) or is it released as v1.0.3?

**Comment by AnErrupTion** [comment] 2024-08-07 17:17
> @AnErrupTion btw since this is a bug fix, is it added onto v1.0.2 (says last updated 6 days ago) or is it released as v1.0.3?

That issue is only present in the `master` branch, so it doesn't need backporting.

**Comment by atrpwq** [comment] 2024-08-07 17:21
alr, btw @DoctorKnowsBetter whered u discover this issue (pwd)

**Comment by atrpwq** [comment] 2024-08-07 17:40
if it works then ill reinstall gentoo if i feel like it, rn js installing the artix iso and balena etcher

**Comment by atrpwq** [comment] 2024-08-07 18:40
@AnErrupTion @DoctorKnowsBetter it works, tyvm :)), i can go back to artix now. ill mark this solved

**Closed** 2024-08-07 18:57 UTC
