### ISSUE TITLE
feature request: to not showing asterisk at all

### ISSUE THREAD

**Issue by xnuk** [fairyglade/ly#642] opened 2024-07-09 22:23 UTC
Same request was #282 (which was rejected). I hope something like `bash -c 'read -s -p "Password: " password'`, which does not move cursor and does not show asterisk at all.

> We don't need a specific option to achieve this, simply replace the asterisk character by a space in the config

Since Zig rewrite (1.0.0), `asterisk = ` cannot set to a space character. Because, well, INI format, you know.

> but I mean, space is visible by cursor movement to the right, so that it is not too hard to guess the length of the password.

Cursor still moves both 1.0 and 0.x.

**Comment by AnErrupTion** [comment] 2024-07-12 20:34
@xnuk This is a duplicate of issue #637.

**Closed by AnErrupTion** 2024-07-12 20:34 UTC
