### ISSUE TITLE
ly 1.0.0 causes multiple issues with Budgie Desktop

### ISSUE THREAD

**Issue by Phantop** [fairyglade/ly#635] opened 2024-07-05 22:04 UTC
Hey!

I just updated to the latest `ly` build on Arch, and it broke a few things for me on Budgie Desktop:
- Font scaling settings are ignored
- Icon theme in ~/.local/share/icons doesn't load
- Custom keybindings aren't available

Downgrading back to 0.6.0 fixed all these issues, so I'm guessing something is odd with how 1.0.0 loads into the DE. Any assistance would be greatly appreciated!

**Comment by AnErrupTion** [comment] 2024-07-28 12:12
@Phantop I've been able to reproduce the issue and can confirm it's an issue with how the `*.desktop` files (which are INI-based) are parsed. This is closely related to #646 because this issue is also about incorrectly parsing comments.

**Comment by AnErrupTion** [comment] 2024-07-30 07:52
This issue is now fixed in master and has been backported for v1.0.2.

**Closed by AnErrupTion** 2024-07-30 07:52 UTC
Labels: bug
